// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NSgaC9-yNFI7L8ErQM35Bs20FoheupA',
    appId: '1:1085826675740:web:dca6e53a247ff993271bd9',
    messagingSenderId: '1085826675740',
    projectId: 'swiftshare-one',
    authDomain: 'swiftshare-one.firebaseapp.com',
    storageBucket: 'swiftshare-one.appspot.com',
    measurementId: 'G-QLETR6NE34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlTP9NbNuxtsLATfvXtAGDau8Gfj9Obwk',
    appId: '1:1085826675740:android:a39b98c0adb46d76271bd9',
    messagingSenderId: '1085826675740',
    projectId: 'swiftshare-one',
    storageBucket: 'swiftshare-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1Lyt4apvOIekKOOObUT8pxYeRQ502e4',
    appId: '1:1085826675740:ios:98e0a51c02484856271bd9',
    messagingSenderId: '1085826675740',
    projectId: 'swiftshare-one',
    storageBucket: 'swiftshare-one.appspot.com',
    iosBundleId: 'com.example.swiftshareOne',
  );
}
